create database io_project;
use io_project;
create table if not exists t_people (id int not null auto_increment, full_name varchar(90) not null, pin varchar(10) default null, primary key(id));
create table if not exists t_mails(id int not null auto_increment, t_people_id int, email_type varchar(5) not null, email varchar(40) default null, primary key(id), foreign key(t_people_id) references t_people(id));
create table if not exists t_addresses(id int not null auto_increment, t_people_id int, addr_type varchar(5) not null, addr_info varchar(300) default null, primary key(id), foreign key(t_people_id) references t_people(id));
insert into t_people (full_name, pin) values ('ivan ivanov', '0123456789');
insert into t_people (full_name, pin) values ('ilian ivanov', '1123456789');
insert into t_people (full_name, pin) values ('stefan ivanov', '2123456789');
insert into t_people (full_name, pin) values ('kalina petkova', '3123456789');
insert into t_people (full_name, pin) values ('petko stoyanov', '4123456789');
insert into t_people (full_name, pin) values ('petya ilieva', '5123456789');
insert into t_people (full_name, pin) values ('temenuga pavlova', '6123456789');
insert into t_people (full_name, pin) values ('nevena manolova', '7123456789');
insert into t_people (full_name, pin) values ('nevena petrova', '9123456789');
insert into t_people (full_name, pin) values ('elizaveta martinova', '9999999999');
insert into t_mails (t_people_id, email_type, email) values (1, 'pers', 'i.ivanov@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (1, 'work', 'i.ivanov@io.org');
insert into t_mails (t_people_id, email_type, email) values (2, 'pers', 'ilian.t.ivanov@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (3, 'pers', 'stefanivanow@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (4, 'work', 'kalinap@abv.bg');
insert into t_mails (t_people_id, email_type, email) values (5, 'pers', '100yanovpe@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (6, 'pers', 'ilieva5ya@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (7, 'pers', 'temenugapavlova@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (8, 'pers', 'nevenamanolova@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (9, 'pers', 'petrovanevena@gmail.com');
insert into t_mails (t_people_id, email_type, email) values (10, 'pers', 'elimart@gmail.com');
insert into t_addresses (t_people_id, addr_type, addr_info) values (1, 'const', 'Sofia, 6 Ivan Vazov str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (2, 'const', 'Sofia, 16 Ivan Vazov str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (3, 'curr', 'Sofia, 63 Atanas Uzunov str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (4, 'const', 'Sofia, 11 Geo Milev str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (5, 'const', 'Sofia, 14 Shipchenski prohod str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (6, 'curr', 'Sofia, 99 Vitosha str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (7, 'const', 'Gabrovo, 12 Ivan Vazov str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (8, 'const', 'Sozopol, 6 Morski skali str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (9, 'const', 'Pernik, 17 Vinkel str.');
insert into t_addresses (t_people_id, addr_type, addr_info) values (10, 'const', 'Sofia, 8 Ivan Vazov str.');
